this.AdventureTags = {

    CanDestroy: function (block) {
        return `{"can_destroy":{"blocks":["${block}"]}}`;
    },

    CanPlaceOn: function () {
        return `{"can_place_on":{"blocks":["air","stone","grass","dirt","cobblestone","planks","sapling","bedrock","flowing_water","water","flowing_lava","lava","sand","gravel","gold_ore","iron_ore","coal_ore","log","leaves","sponge","glass","lapis_ore","lapis_block","dispenser","sandstone","noteblock","golden_rail","detector_rail","sticky_piston","web","tallgrass","deadbush","piston","wool","brown_mushroom","red_mushroom","gold_block","iron_block","double_stone_slab","stone_slab","brick_block","tnt","bookshelf","mossy_cobblestone","obsidian","torch","fire","mob_spawner","oak_stairs","chest","redstone_wire","diamond_ore","diamond_block","crafting_table","farmland","furnace","lit_furnace","standing_sign","ladder","rail","stone_stairs","wall_sign","lever","stone_pressure_plate","wooden_pressure_plate","redstone_ore","lit_redstone_ore","unlit_redstone_torch","redstone_torch","stone_button","snow_layer","ice","snow","cactus","clay","jukebox","fence","pumpkin","netherrack","soul_sand","glowstone","portal","lit_pumpkin","unpowered_repeater","powered_repeater","stained_glass","trapdoor","monster_egg","stonebrick","brown_mushroom_block","red_mushroom_block","iron_bars","glass_pane","melon_block","pumpkin_stem","melon_stem","vine","fence_gate","brick_stairs","stone_brick_stairs","mycelium","waterlily","nether_brick","nether_brick_fence","nether_brick_stairs","enchanting_table","end_portal","end_portal_frame","end_stone","dragon_egg","redstone_lamp","lit_redstone_lamp","double_wooden_slab","wooden_slab","cocoa","sandstone_stairs","emerald_ore","ender_chest","tripwire_hook","tripwire","emerald_block","spruce_stairs","birch_stairs","jungle_stairs","command_block","beacon","cobblestone_wall","wooden_button","anvil","trapped_chest","light_weighted_pressure_plate","heavy_weighted_pressure_plate","unpowered_comparator","powered_comparator","daylight_detector","redstone_block","quartz_ore","hopper","quartz_block","quartz_stairs","activator_rail","dropper","stained_hardened_clay","stained_glass_pane","log2","log2","acacia_stairs","dark_oak_stairs","slime","barrier","iron_trapdoor","prismarine","hay_block","carpet","hardened_clay","coal_block","packed_ice","double_plant","prismarine","barrier","red_sandstone","iron_trapdoor","concrete","double_stone_slab","double_stone_slab2","double_stone_slab3","double_stone_slab4","amethyst_block"]}}`;
    }

}